#!/usr/bin/env python3
"""
Generate TypeScript/Python/Go code from JSON-LD type registry.

Usage:
    python codegen.py

Generates:
    - generated/TypeMappings.ts (for xlsform2lstsv)
    - generated/type_mappings.py (for survey2ddi)
    - generated/type_mappings.go (for qwacback)
    - generated/TYPE_EQUIVALENCE.md (documentation)
"""

import json
import re
from pathlib import Path
from typing import Any

_IDENT_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

def _ts_key(name: str) -> str:
    """Quote TS object keys when they contain non-identifier chars."""
    return name if _IDENT_RE.match(name) else json.dumps(name)

def _slug(at_id: str) -> str:
    """Strip namespace prefix from @id: 'type:integer' -> 'integer'."""
    return at_id.split(":", 1)[1] if ":" in at_id else at_id

def load_registry(path: Path) -> dict[str, Any]:
    """Load and parse JSON-LD registry. Keyed by full @id to avoid namespace collision."""
    with open(path) as f:
        data = json.load(f)

    registry = {}
    for item in data.get("@graph", []):
        registry[item["@id"]] = item
    return registry

def generate_typescript(registry: dict[str, Any], output: Path):
    """Generate TypeScript type mappings for xlsform2lstsv."""
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: survey-types.jsonld",
        " * Generated by: codegen.py",
        " */",
        "",
        "export type TypeKind = 'question' | 'metadata' | 'structural';",
        "",
        "export interface TypeMapping {",
        "  kind: TypeKind;",
        "  limeSurveyType: string | null;",
        "  supported: boolean;",
        "  supportsOther?: boolean;",
        "  answerClass?: 'A' | 'SQ' | null;",
        "  requiresListName?: boolean;",
        "}",
        "",
        "export const TYPE_MAPPINGS: Record<string, TypeMapping> = {",
    ]

    def emit(name: str, kind: str, data: dict):
        ls = data.get("limesurvey", {})
        xls = data.get("xlsform", {})
        supported = ls.get("supported", True) if ls else True
        # If typeCode missing and not explicitly supported=true, treat as unsupported
        if ls.get("typeCode") is None and "supported" not in ls:
            supported = False
        lines.append(f"  {_ts_key(name)}: {{")
        lines.append(f"    kind: {json.dumps(kind)},")
        lines.append(f"    limeSurveyType: {json.dumps(ls.get('typeCode'))},")
        lines.append(f"    supported: {'true' if supported else 'false'},")
        if ls.get("supportsOther"):
            lines.append(f"    supportsOther: true,")
        if ls.get("answerClass"):
            lines.append(f"    answerClass: {json.dumps(ls['answerClass'])},")
        if xls.get("requiresListName"):
            lines.append(f"    requiresListName: true,")
        lines.append("  },")

    kind_map = {
        "QuestionType": "question",
        "MetadataType": "metadata",
        "StructuralType": "structural",
    }
    for type_id, data in registry.items():
        kind = kind_map.get(data.get("@type"))
        if kind is None:
            continue
        xlsform = data["xlsform"]["typeString"]
        emit(xlsform, kind, data)
        for alias in data["xlsform"].get("aliases", []):
            emit(alias, kind, data)

    lines.append("};")
    lines.append("")

    output.write_text("\n".join(lines))

def _is_supported_question(data: dict) -> bool:
    """LimeSurvey TSV emittable (xlsform2lstsv perspective)."""
    if data.get("@type") != "QuestionType":
        return False
    ls = data.get("limesurvey", {})
    if ls.get("supported") is False:
        return False
    return ls.get("typeCode") is not None

def _is_ddi_emittable(data: dict) -> bool:
    """DDI XML emittable (survey2ddi perspective). True iff entry has a ddi.intrvl."""
    if data.get("@type") not in ("QuestionType", "MetadataType"):
        return False
    ddi = data.get("ddi", {})
    return bool(ddi.get("intrvl"))

def generate_python(registry: dict[str, Any], output: Path):
    """Generate Python type mappings for survey2ddi."""
    lines = [
        '"""',
        "GENERATED CODE - DO NOT EDIT",
        "Source: survey-types.jsonld",
        "Generated by: codegen.py",
        '"""',
        "",
        "# XLSForm type → standardized type",
        "TYPE_MAP: dict[str, str] = {",
    ]

    # TYPE_MAP includes ALL QuestionType entries (LS-unsupported types like `range`
    # are still DDI-emittable for survey2ddi). Aliases map to canonical slug.
    for type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue

        xlsform = data["xlsform"]["typeString"]
        canon = _slug(type_id)  # "type:integer" -> "integer"
        lines.append(f'    "{xlsform}": "{canon}",')

        for alias in data["xlsform"].get("aliases", []):
            lines.append(f'    "{alias}": "{canon}",')

    lines.append("}")
    lines.append("")
    lines.append("# XLSForm metadata types (silently skipped during conversion)")
    lines.append("METADATA_TYPES: set[str] = {")
    for type_id, data in registry.items():
        if data.get("@type") != "MetadataType":
            continue
        lines.append(f'    "{data["xlsform"]["typeString"]}",')
    lines.append("}")
    lines.append("")
    lines.append("# XLSForm types that are recognized but unsupported in LimeSurvey TSV pipeline")
    lines.append("UNSUPPORTED_TYPES: set[str] = {")
    for type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        if data.get("limesurvey", {}).get("supported") is False:
            lines.append(f'    "{data["xlsform"]["typeString"]}",')
    lines.append("}")
    lines.append("")
    lines.append("# Structural types (begin_group, end_group, begin_repeat, end_repeat)")
    lines.append("STRUCTURAL_TYPES: set[str] = {")
    for type_id, data in registry.items():
        if data.get("@type") != "StructuralType":
            continue
        xls = data.get("xlsform", {}).get("typeString")
        if xls:
            lines.append(f'    "{xls}",')
    lines.append("}")
    lines.append("")
    lines.append("# Standardized type → (intrvl, format_type). Filter: DDI-emittable (has ddi.intrvl).")
    lines.append("DDI_TYPE_MAP: dict[str, tuple[str, str]] = {")

    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue

        ddi = data["ddi"]
        intrvl = ddi.get("intrvl", "discrete")
        fmt_type = ddi.get("formatType", "character")
        lines.append(f'    "{_slug(type_id)}": ("{intrvl}", "{fmt_type}"),')

    lines.append("}")
    lines.append("")

    lines.append("# Standardized type → responseDomainType for <qstn>")
    lines.append("RESPONSE_DOMAIN_MAP: dict[str, str] = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        rd = data["ddi"].get("responseDomainType")
        if rd:
            lines.append(f'    "{_slug(type_id)}": "{rd}",')
    lines.append("}")
    lines.append("")

    lines.append("# Standardized type → measurement level")
    lines.append("MEASURE_MAP: dict[str, str] = {")

    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue

        ddi = data.get("ddi", {})
        # Try to derive measurement level from intrvl
        intrvl = ddi.get("intrvl", "")
        xls = data["xlsform"]["typeString"]
        if intrvl == "nominal" or (intrvl == "discrete" and xls in ["select_one", "select_multiple", "select_one_from_file", "select_multiple_from_file"]):
            measure = "nominal"
        elif intrvl == "ordinal" or xls == "rank":
            measure = "ordinal"
        elif xls in ("date", "time", "datetime"):
            measure = "interval"
        elif intrvl == "interval":
            measure = "interval"
        elif intrvl == "contin":
            measure = "ratio"
        else:
            continue  # No measure for this type

        lines.append(f'    "{_slug(type_id)}": "{measure}",')

    lines.append("}")
    lines.append("")

    output.write_text("\n".join(lines))

def generate_go(registry: dict[str, Any], output: Path):
    """Generate Go type mappings for qwacback."""
    lines = [
        "// GENERATED CODE - DO NOT EDIT",
        "// Source: survey-types.jsonld",
        "// Generated by: codegen.py",
        "",
        "package converter",
        "",
        "type TypeMapping struct {",
        "    XLSForm          string",
        "    LimeSurvey       string",
        "    DDIIntrvl        string",
        "    DDIFormatType    string",
        "    ResponseDomain   string",
        "    RoundTripSafe    bool",
        "    DataColumns      string // '1', 'n-choices', etc.",
        "}",
        "",
        "var TypeRegistry = map[string]TypeMapping{",
    ]

    for type_id, data in registry.items():
        if not _is_supported_question(data):
            continue

        xlsform = data["xlsform"]["typeString"]
        ls = data.get("limesurvey", {})
        ddi = data.get("ddi", {})
        trans = data.get("transformation", {})

        data_cols = str(trans.get("dataColumns", ""))

        lines.append(f'    "{xlsform}": {{')
        lines.append(f'        XLSForm:       "{xlsform}",')
        lines.append(f'        LimeSurvey:    "{ls.get("typeCode", "")}",')
        lines.append(f'        DDIIntrvl:     "{ddi.get("intrvl", "")}",')
        lines.append(f'        DDIFormatType: "{ddi.get("formatType", "")}",')
        lines.append(f'        ResponseDomain: "{ddi.get("responseDomainType", "")}",')
        lines.append(f'        RoundTripSafe: {str(trans.get("roundTripSafe", False)).lower()},')
        lines.append(f'        DataColumns:   "{data_cols}",')
        lines.append("    },")

    lines.append("}")
    lines.append("")

    output.write_text("\n".join(lines))

def generate_validation_docs(registry: dict[str, Any], output: Path):
    """Generate human-readable documentation."""
    lines = [
        "# Survey Type Equivalence Matrix",
        "",
        "**Generated from:** `survey-types.jsonld`  ",
        "**Last updated:** (auto-generated)",
        "",
        "This document shows how question types map across different formats in the CDL survey ecosystem.",
        "",
        "## Quick Reference Table",
        "",
        "| XLSForm | LimeSurvey | DDI | Round-trip Safe | Data Structure | Key Warnings |",
        "|---------|------------|-----|-----------------|----------------|--------------|",
    ]

    for type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue

        xlsform = data["xlsform"]["typeString"]
        ls_type = data.get("limesurvey", {}).get("typeCode", "—")

        ddi_info = data.get("ddi", {})
        if "structure" in ddi_info:
            ddi_str = f"`varGrp[@type='{ddi_info['structure']['type']}']`"
        else:
            ddi_str = f"`var[@intrvl='{ddi_info.get('intrvl', '')}']`"

        trans = data.get("transformation", {})
        safe = "✅" if trans.get("roundTripSafe") else "⚠️"
        data_struct = trans.get("dataStructure", "—")

        warnings = trans.get("warnings", [])
        warning_str = warnings[0] if warnings else "—"

        lines.append(
            f"| `{xlsform}` | `{ls_type}` | {ddi_str} | {safe} | {data_struct} | {warning_str} |"
        )

    lines.append("")
    lines.append("## Detailed Type Information")
    lines.append("")

    for type_id, data in sorted(registry.items()):
        if data.get("@type") != "QuestionType":
            continue

        label = data.get("skos:prefLabel", type_id)
        xlsform = data["xlsform"]["typeString"]

        lines.append(f"### {label} (`{xlsform}`)")
        lines.append("")

        # Aliases
        aliases = data["xlsform"].get("aliases", [])
        if aliases:
            lines.append(f"**Aliases:** `{'`, `'.join(aliases)}`")
            lines.append("")

        # Platform support
        lines.append("**Platform Mappings:**")
        ls = data.get("limesurvey", {})
        ddi = data.get("ddi", {})
        lines.append(f"- **LimeSurvey:** Type `{ls.get('typeCode', 'N/A')}`")
        if ls.get("answerClass"):
            lines.append(f"  - Answer class: `{ls['answerClass']}`")
        if ls.get("supportsOther"):
            lines.append(f"  - Supports 'other' option: ✅")
        lines.append(f"- **DDI:** `intrvl=\"{ddi.get('intrvl', '')}\"`, `formatType=\"{ddi.get('formatType', '')}\"`")
        if "structure" in ddi:
            lines.append(f"  - Structure: `<varGrp type=\"{ddi['structure']['type']}\">` with {ddi['structure']['memberVars']}")
        lines.append("")

        # Constraints
        constraints = data.get("constraints", {})
        if constraints:
            lines.append("**Constraints:**")
            if "maxNameLength" in constraints:
                lines.append(f"- Variable name: max {constraints['maxNameLength']} chars, pattern `{constraints.get('namePattern', '')}`")
            if "maxChoiceCodeLength" in constraints:
                lines.append(f"- Choice codes: max {constraints['maxChoiceCodeLength']} chars, pattern `{constraints.get('choiceCodePattern', '')}`")
            if "warnings" in constraints:
                for w in constraints["warnings"]:
                    lines.append(f"- ⚠️ {w}")
            lines.append("")

        # Transformation
        trans = data.get("transformation", {})
        lines.append("**Transformation:**")
        lines.append(f"- Round-trip safe: {'✅ Yes' if trans.get('roundTripSafe') else '⚠️ No'}")
        lines.append(f"- Lossless: {'✅ Yes' if trans.get('lossless') else '⚠️ No'}")
        lines.append(f"- Data columns: {trans.get('dataColumns', '?')}")
        lines.append(f"- Data structure: {trans.get('dataStructure', '?')}")

        if trans.get("structureChanges"):
            lines.append("")
            lines.append("**Structure Changes During Transformation:**")
            for change in trans["structureChanges"]:
                lines.append(f"- {change['from']} → {change['to']}: {change['change']}")

        if trans.get("warnings"):
            lines.append("")
            lines.append("**Warnings:**")
            for w in trans["warnings"]:
                lines.append(f"- ⚠️ {w}")

        lines.append("")
        lines.append("---")
        lines.append("")

    # Add structural types
    lines.append("## Structural Types")
    lines.append("")
    lines.append("These are not question types but affect survey structure:")
    lines.append("")

    for type_id, data in sorted(registry.items()):
        if data.get("@type") != "StructuralType":
            continue

        label = data.get("skos:prefLabel", type_id)
        xlsform = data["xlsform"]["typeString"]

        lines.append(f"### {label} (`{xlsform}`)")
        lines.append("")

        ls = data.get("limesurvey", {})
        if "supported" in ls and not ls["supported"]:
            lines.append("⛔ **Not supported in LimeSurvey**")
        elif ls.get("supportsNesting") is False:
            lines.append("⚠️ **LimeSurvey does not support nested groups** (groups are flattened)")
        lines.append("")

        ddi = data.get("ddi", {})
        if ddi.get("preservation") == "conditional":
            lines.append("**DDI Preservation:** Conditional")
            lines.append("")
            for cond in ddi.get("conditions", []):
                lines.append(f"- **If** {cond['if']}  ")
                lines.append(f"  **Then:** {cond['then']}")
            lines.append("")

        trans = data.get("transformation", {})
        if trans.get("warnings"):
            lines.append("**Warnings:**")
            for w in trans["warnings"]:
                lines.append(f"- ⚠️ {w}")
            lines.append("")

        lines.append("---")
        lines.append("")

    output.write_text("\n".join(lines))

def generate_appearances(registry: dict[str, Any], output: Path):
    """Emit Appearance entries as TS map for xlsform2lstsv."""
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: survey-types.jsonld",
        " * Generated by: codegen.py",
        " */",
        "",
        "export interface AppearanceSpec {",
        "  supported: boolean;",
        "  behavior: 'handled' | 'warn';",
        "  validForTypes?: string[];",
        "  lsEffect: string;",
        "  lsTypeOverride?: string;",
        "}",
        "",
        "export const APPEARANCES: Record<string, AppearanceSpec> = {",
    ]
    # Build alias map: typeString -> [typeString, ...aliases]
    alias_map: dict[str, list[str]] = {}
    for data in registry.values():
        if data.get("@type") != "QuestionType":
            continue
        xls = data.get("xlsform", {})
        primary = xls.get("typeString")
        if not primary:
            continue
        alias_map[primary] = [primary] + list(xls.get("aliases", []))

    def expand_types(types: list[str]) -> list[str]:
        out: list[str] = []
        seen: set[str] = set()
        for t in types:
            for x in alias_map.get(t, [t]):
                if x not in seen:
                    seen.add(x)
                    out.append(x)
        return out

    for type_id, data in registry.items():
        if data.get("@type") != "Appearance":
            continue
        aid = data["xlsform"]["appearanceString"]
        lines.append(f"  {json.dumps(aid)}: {{")
        lines.append(f"    supported: {'true' if data['supported'] else 'false'},")
        lines.append(f"    behavior: {json.dumps(data['behavior'])},")
        if data.get("validForTypes"):
            expanded = expand_types(data["validForTypes"])
            lines.append(f"    validForTypes: {json.dumps(expanded)},")
        lines.append(f"    lsEffect: {json.dumps(data['lsEffect'])},")
        if data.get("lsTypeOverride"):
            lines.append(f"    lsTypeOverride: {json.dumps(data['lsTypeOverride'])},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    output.write_text("\n".join(lines))

def generate_conventions(registry: dict[str, Any], output: Path):
    """Emit global conventions + column map as TS module."""
    conv = {}
    col_map = []
    for type_id, data in registry.items():
        t = data.get("@type")
        if t == "GlobalConvention":
            slug = data["@id"].split(":", 1)[1]
            conv[slug] = data.get("rule", {})
        elif t == "XLSFormColumnMap":
            col_map = data.get("map", [])
    out = {
        "$comment": "GENERATED - DO NOT EDIT. Source: survey-types.jsonld",
        "conventions": conv,
        "xlsformColumnMap": col_map,
    }
    output.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")

def generate_examples_index(registry: dict[str, Any], base_dir: Path, output: Path):
    """Emit examples_index.json — flat list of presentation variants with embedded XLSForm payload."""
    index = []
    for type_id, data in registry.items():
        if data.get("@type") != "PresentationVariant":
            continue
        ex_path = data.get("examplePath")
        if not ex_path:
            continue
        full = base_dir / ex_path
        if not full.exists():
            continue
        with open(full) as f:
            xlsform = json.load(f)
        qw = data.get("qwacback", {})
        index.append({
            "id": qw.get("exampleId", type_id),
            "answerType": qw.get("answerType"),
            "label": data.get("skos:prefLabel"),
            "concept": data.get("concept", {}),
            "presentation": data.get("presentation", {}),
            "broader": data.get("skos:broader", {}).get("@id"),
            "xlsform": xlsform,
        })
    with open(output, "w") as f:
        json.dump({"variants": index}, f, indent=2, ensure_ascii=False)
        f.write("\n")

if __name__ == "__main__":
    base_dir = Path(__file__).parent
    registry_path = base_dir / "survey-types.jsonld"
    output_dir = base_dir / "generated"
    output_dir.mkdir(exist_ok=True)

    print("Loading registry from survey-types.jsonld...")
    registry = load_registry(registry_path)
    print(f"  Loaded {len(registry)} types")

    print("\nGenerating code...")
    generate_typescript(registry, output_dir / "TypeMappings.ts")
    print("  ✅ TypeMappings.ts (for xlsform2lstsv)")

    generate_python(registry, output_dir / "type_mappings.py")
    print("  ✅ type_mappings.py (for survey2ddi)")

    generate_go(registry, output_dir / "type_mappings.go")
    print("  ✅ type_mappings.go (for qwacback)")

    generate_validation_docs(registry, output_dir / "TYPE_EQUIVALENCE.md")
    print("  ✅ TYPE_EQUIVALENCE.md (documentation)")

    generate_examples_index(registry, base_dir, output_dir / "examples_index.json")
    print("  ✅ examples_index.json (for wp_eins + qwacback)")

    generate_appearances(registry, output_dir / "Appearances.ts")
    print("  ✅ Appearances.ts (for xlsform2lstsv)")

    generate_conventions(registry, output_dir / "conventions.json")
    print("  ✅ conventions.json (for xlsform2lstsv)")

    print("\n✨ Code generation complete!")
    print(f"\nNext steps:")
    print(f"  1. Review generated files in {output_dir}")
    print(f"  2. Copy TypeMappings.ts to xlsform2lstsv/src/processors/")
    print(f"  3. Copy type_mappings.py to survey2ddi/survey2ddi_core/")
    print(f"  4. Copy type_mappings.go to qwacback/internal/converter/")
    print(f"  5. Update imports in those projects to use generated code")
